name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      SPRING_PROFILES_ACTIVE: prod
      frontend.url: https://adoptdontshop.duckdns.org
    steps:
      - uses: actions/checkout@v3

      - name: Test SSH Connection
        run: |
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -vvv -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.GCP_USER }}@${{ secrets.GCP_INSTANCE_IP }} "echo 'SSH Connection Success'"

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Create .env.production on GCP
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.GCP_USER }}@${{ secrets.GCP_INSTANCE_IP }} << 'EOF'
          echo "${{ secrets.GCP_ENV_PRODUCTION }}" > /home/adoptdontshopinfo/actions-runner/adopt-dont-shop/s25-pet-adoption-team-3/s25-pet-adoption-team-3/pet-adoption-frontend/.env.production
          echo "${{ secrets.GOOGLE_MAPS_API_KEY }}" >> /home/adoptdontshopinfo/actions-runner/adopt-dont-shop/s25-pet-adoption-team-3/s25-pet-adoption-team-3/pet-adoption-frontend/.env.production
          chmod 600 /home/adoptdontshopinfo/actions-runner/adopt-dont-shop/s25-pet-adoption-team-3/s25-pet-adoption-team-3/pet-adoption-frontend/.env.production
          echo "✅ .env.production successfully created on GCP"
          EOF

      - name: Cleanup
        run: |
          docker system prune -a -f --filter "until=24h"

      - name: Build
        run: |
          docker compose -f docker/ci.docker-compose.yml build

      - name: Deploy
        run: |
          docker compose -f docker/ci.docker-compose.yml down
          docker compose -f docker/ci.docker-compose.yml up -d --build

      - name: Cleanup SSH Key
        run: rm -f private_key.pem
